### PR TITLE
Update Calculator.cpp

### PR DESCRIPTION
**Pull request by photonbeam17**
Ok, restored your version

### CODE REVIEW

**Comment by photonbeam17** [comment]
Some errors; so I'll try to fix

**Comment by Ayushmaan2001** [comment]
> Some errors; so I'll try to fix

where??

**Comment by photonbeam17** [comment]
on line 53 there's a stray bracket and cin >>cl wasn't defined. i rewrote it like this
```
#include <iostream>
#include <math.h>
using namespace std;
int main() {
  //Calculator

  //Variables
  double num1, num2;
  int choice;
  bool x = true;
  string s;

  while (x) {
    //Input
    cout << "Enter number 1: ";
    cin >> num1;
    cout << "Enter number 2: ";
    cin >> num2;

    //Select Function
    cout << "Enter Your choice:\n1. Addition\n2. Subtraction\n3. Multiplication\n4. Division\n5. Modulus\n. Enter Your choice number- ";

    cin >> choice;
    //Output

      switch(choice)
      {

        //Addition
        case 1:
        cout << num1 << " + " << num2 << " = " << num1 + num2 << endl;
        break;

        //Subtraction
        case 2:
        cout << num1 << " - " << num2 << " = " << num1 - num2 << endl;
        break;

        //Multiplication
        case 3:
        cout << num1 << " * " << num2 << " = " << num1 * num2 << endl;
        break;

        //Division
        case 4:
        cout << num1 << " / " << num2 << " = " << num1 / num2 << endl;
        break;

        //Modulus

        case 5:
        cout<< num1 << " % " << num2 << " = " <<fmod(num1,num2) << endl;
        break;

        default:
        cout << "Invalid Entry!!";
      }

    cout << "Would you like to keep doing calculations? (y/n)" << endl;
    cin >> s;
    if (s == "y") {
      cout << "Okay!" << endl;
      x = true;
    } else if (s == "n") {
      cout << "Goodbye!" << endl;
      x = false;
    } else {
      cout << "Goodbye!" << endl;
      x = false;
    }


  }
  


}
```

**Comment by photonbeam17** [comment]
will merge on seperate pull request

**Pull request closed without merging**
